name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          # Добавляем GitHub в known_hosts для git pull на сервере
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /mnt/servers/docker/nginx/femc-page-nuxt-master
          # Меняем URL репозитория на SSH (если нужно)
          git remote set-url origin git@github.com:ваш_username/репозиторий.git
          # Принудительный pull сбросом изменений
          git fetch --all
          git reset --hard origin/master
          # Перезапуск Docker
          docker compose up -d --build
          EOF
